export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const DELETE_PARTICIPANT = 'DELETE_PARTICIPANT';
export const RENAME_PARTICIPANT = 'RENAME_PARTICIPANT';
export const ADD_SCORE = 'ADD_SCORE';
export const RESET_SCORES = 'RESET_SCORES';
export const RESET_ALL = 'RESET_ALL';
export const MOVE_UP_PARTICIPANT = 'MOVE_UP_PARTICIPANT';
export const MOVE_DOWN_PARTICIPANT = 'MOVE_DOWN_PARTICIPANT';

export const REVERT_STATE = 'REVERT_STATE';


export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
